# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-03 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodycams', '0002_auto_20181026_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodycamtag',
            name='shooting',
        ),
        migrations.DeleteModel(
            name='BodycamTag',
        ),
    ]
