# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-12 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodycams', '0003_auto_20181102_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodycam',
            name='video',
            field=models.CharField(max_length=100000),
        ),
    ]
