# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-01 03:42
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('bodycams', '0004_auto_20181112_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodycam',
            name='created',
            field=models.DateTimeField(default=timezone.now(), editable=False, verbose_name='Creation Date'),
            preserve_default=False,
        ),
    ]
