# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-01 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodycams', '0005_bodycam_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodycam',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Creation Date'),
        ),
    ]
