# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodycams', '0006_auto_20181130_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodycam',
            name='shooting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodycams', to='roster.Shooting'),
        ),
    ]
