# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-29 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('created', models.DateTimeField(editable=False, verbose_name='Publish Date')),
                ('modified', models.DateTimeField()),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
