# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-09 02:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 22, 33, 1, 519867), editable=False, verbose_name='Publish Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 8, 22, 33, 11, 279964), editable=False, verbose_name='Last Modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='modified',
            field=models.DateTimeField(editable=False, verbose_name='Last Modified'),
        ),
    ]
