# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-10 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_draft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='mediafiles/uploads/DonutsDonut.png', upload_to='mediafiles/'),
        ),
    ]
