# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-10 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181009_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='DonutsDonut.png', upload_to='mediafiles/'),
        ),
    ]
