# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-10 21:12
from __future__ import unicode_literals

import blog.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181009_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='DonutsDonut.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/uploads/', location='C:\\Users\\pedro\\OneDrive\\Documents\\Heroku\\DonutProject\\DonutProject\\config\\media/uploads/'), upload_to=blog.models.image_directory_path),
        ),
    ]
