# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-10 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181010_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_length',
            field=models.TextField(default='1 min read', max_length=20, verbose_name='Article Length'),
            preserve_default=False,
        ),
    ]
