# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-10 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_read_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_length',
            field=models.CharField(max_length=20, verbose_name='Article Length'),
        ),
    ]
