# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-15 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181010_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.CharField(default='Donutoperator', max_length=100, verbose_name='Authors'),
        ),
    ]
