# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-12 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_auto_20180911_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooting',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Unknown')], default=0, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shooting',
            name='race',
            field=models.IntegerField(choices=[(0, 'Native American'), (1, 'Asian'), (2, 'Black'), (3, 'Native Hawaiian or Other Pacific Islander'), (4, 'White'), (5, 'Hispanice/Latino'), (6, 'None Given'), (7, 'Other')], verbose_name='Race'),
        ),
    ]
