# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-12 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_auto_20180911_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Text'),
        ),
    ]
