# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-16 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_auto_20180912_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('shooting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='roster.Shooting')),
            ],
        ),
    ]
