# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-22 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shooting',
            name='race',
            field=models.IntegerField(choices=[(0, 'Native American'), (1, 'Asian'), (2, 'Black'), (3, 'Native Hawaiian or Other Pacific Islander'), (4, 'White'), (5, 'Hispanic/Latino'), (6, 'None Given'), (7, 'Other')], verbose_name='Race'),
        ),
    ]
