# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-22 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_auto_20180921_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Text'),
        ),
    ]
