# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-29 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_auto_20180921_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooting',
            name='unfiltered_video_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Unfiltered Video Url'),
        ),
    ]
