# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-03 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bodycams', '0003_auto_20181102_2147'),
        ('roster', '0010_auto_20181008_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='bodycam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='bodycams.Bodycam'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='shooting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='roster.Shooting'),
        ),
    ]
