# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_auto_20181130_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooting',
            name='has_bodycam',
            field=models.BooleanField(default=False, verbose_name='Has Bodycam'),
        ),
    ]
