# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-11 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodycams', '0007_auto_20181205_1158'),
        ('roster', '0014_shooting_has_bodycam'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMMTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Text')),
                ('bodycams', models.ManyToManyField(related_name='mmtags', to='bodycams.Bodycam')),
                ('shootings', models.ManyToManyField(related_name='mmtags', to='roster.Shooting')),
            ],
        ),
    ]
