# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-12 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodycams', '0007_auto_20181205_1158'),
        ('roster', '0015_mmmtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mmmtag',
            name='bodycams',
        ),
        migrations.RemoveField(
            model_name='mmmtag',
            name='shootings',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='bodycam',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='shooting',
        ),
        migrations.AddField(
            model_name='tag',
            name='bodycams',
            field=models.ManyToManyField(related_name='tags', to='bodycams.Bodycam'),
        ),
        migrations.AddField(
            model_name='tag',
            name='shootings',
            field=models.ManyToManyField(related_name='tags', to='roster.Shooting'),
        ),
        migrations.DeleteModel(
            name='MMMTag',
        ),
    ]
