# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-18 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0017_tip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Tip'),
        ),
    ]
