# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-24 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0018_auto_20181217_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000, verbose_name='Tip')),
                ('created', models.DateTimeField(editable=False)),
            ],
        ),
    ]
