# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 19:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0019_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='shooting',
            name='specially_exempted_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
